name: month_year_dropdown
description: "A Flutter package for creating dropdown menus to select months and years. This package provides a customizable dropdown widget that allows users to choose from a list of months or years, enhancing the user experience in date-related inputs."
version: 1.0.3
homepage:  https://github.com/Krish0034/month_year_dropdown

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
#
#  plugin:
#    platforms:
#      android:
#        package: com.example.month_year_dropdown
#        pluginClass: MonthYearDropdownPlugin
#      ios:
#        pluginClass: MonthYearDropdownPlugin
